name: Publish

on:
  release:
    types: [published]

jobs:
  publish-vscode:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: "Publish to VS Code: Marketplace"
      run: npx @vscode/vsce publish -p ${{ secrets.VSCE_TOKEN }}
      
  publish-openvsx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Publish to Open VSX
      run: npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}
